name: food_inspector_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.2

  firebase_core: ^2.27.1

  # Auth
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1

  # Store
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
